---
- name: Restart authentik-caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted

- name: Restart authentik-radius
  ansible.builtin.systemd:
    name: authentik-radius
    state: restarted
